### ISSUE TITLE
When running the analyzer against any file i get AttributeError 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kalimist123** [savioabuga/piianalyzer#8]
When running the analyzer against any file i get AttributeError 'str' object has no attribute 'decode'.
Windows 2010. Python 3.5

> > > filepath = 'C:/Users/###########/Documents/RStuff/addressestext.txt'
> > > piianalyzer = PiiAnalyzer(filepath)
> > > analysis = piianalyzer.analysis()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users###########\AppData\Local\Programs\Python\Python35\lib\site-packages\piianalyzer\analyzer.py", line 26, in analysis
> > >     for row in reader:
> > >   File "C:\Users###########\AppData\Local\Programs\Python\Python35\lib\site-packages\unicodecsv\py3.py", line 55, in **next**
> > >     return self.reader.**next**()
> > >   File "C:\Users###########\AppData\Local\Programs\Python\Python35\lib\site-packages\unicodecsv\py3.py", line 51, in <genexpr>
> > >     f = (bs.decode(encoding, errors=errors) for bs in f)
> > > AttributeError: 'str' object has no attribute 'decode'

**Comment by harmeshm** [comment]
getting the same error - any solutions?

**Comment by sgupta227** [comment]
Getting same error can any one help me ? or any suggestions ?

**Comment by RipPennell** [comment]
Had the same issue but was able to fix it.

Open up the downloaded package and go to analyzer.py and change it to:

import csv
from commonregex import CommonRegex
from nltk.tag.stanford import StanfordNERTagger


class PiiAnalyzer(object):
    def __init__(self, filepath):
        self.filepath = filepath
        self.parser = CommonRegex()
        self.standford_ner = StanfordNERTagger('classifiers/english.conll.4class.distsim.crf.ser.gz')

    def analysis(self):
        people = []
        organizations = []
        locations = []
        emails = []
        phone_numbers = []
        street_addresses = []
        credit_cards = []
        ips = []
        data = []

        with open(self.filepath, 'r') as filedata:
            reader = csv.reader(filedata)

            for row in reader:
                data.extend(row)
                for text in row:
                    emails.extend(self.parser.emails(text))
                    phone_numbers.extend(self.parser.phones("".join(text.split())))
                    street_addresses.extend(self.parser.street_addresses(text))
                    credit_cards.extend(self.parser.credit_cards(text))
                    ips.extend(self.parser.ips(text))

        for title, tag in self.standford_ner.tag(set(data)):
            if tag == 'PERSON':
                people.append(title)
            if tag == 'LOCATION':
                locations.append(title)
            if tag == 'ORGANIZATION':
                organizations.append(title)

        return {'people': people, 'locations': locations, 'organizations': organizations,
                'emails': emails, 'phone_numbers': phone_numbers, 'street_addresses': street_addresses,
                'credit_cards': credit_cards, 'ips': ips
                }

**Comment by rafaelagrc** [comment]
I solved this error by `import csv` in file _'analyzer.py'_ instead of doing `import unicodecsv as csv`
